### ISSUE TITLE
About retrieved text 

### ISSUE THREAD

**Issue by HuichiZhou** [sleeepeer/PoisonedRAG#14]
Nice work!

I wonder why the ground-truth texts are not among the top 10 results for many queries?

**Comment by sleeepeer** [comment]
Hi! Thanks for your interest in our paper and thanks for pointing it out!

I tested what you said and the Top-10 accuracy (whether ground truth appear in top-10) is **0.449**, **0.824** and **0.294** for NQ, HotpotQA and MSMARCO.

We used [BEIR](https://github.com/beir-cellar/beir) dataset and the above results are what I tested on it. It does seem that many ground-truth texts are not among the top 10. Although it does not affect the experiment results since most of our poisoned texts could achieve the top-1 in retrieval, this is still an interesting finding. Maybe it's a limitation of the dataset itself and I think maybe we could find some related discussion in [BEIR issues](https://github.com/beir-cellar/beir/issues).

We could discuss together to figure it out if you feel interested. And feel free to leave this issue open here to see if others have some comments.

Thanks again for your attention in our paper!
